controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

when@dev:
    # database
    dev_db_connection:
        path: /dev/db/connection
        controller: App\Development\Controller\Database::connection
    dev_db_test_data:
        path: /dev/db/test-data
        controller: App\Development\Controller\Database::testDb
    dev_db_fetch_data:
        path: /dev/db/fetch-data
        controller: App\Development\Controller\Database::fetchData
    dev_db_fetch_entity_list:
        path: /dev/db/fetch-entity-list
        controller: App\Development\Controller\Database::fetchEntityList

    # sqlFilter

    # entities
    dev_entities_get_entities:
        path: /dev/entities/get-entities
        controller: App\Development\Controller\Entities::getEntities
    dev_entities_entity_by_key:
        path: /dev/entities/get-entity-by-key
        controller: App\Development\Controller\Entities::getEntityByEntityKey
    dev_entities_pre_render:
        path: /dev/entities/pre-render
        controller: App\Development\Controller\Entities::preRenderEntity
    dev_entities_search_ext_overview:
        path: /dev/entities/search-ext-overview
        controller: App\Development\Controller\Entities::searchExtendedEntityOverview

    # services
    dev_services_locator:
        path: /dev/services/locator
        controller: App\Development\Controller\Services::locator
    dev_services_type_reader:
        path: /dev/services/type-reader
        controller: App\Development\Controller\Services::entityTypeReader
    dev_services_html:
      path: /dev/services/html
      controller: App\Development\Controller\Services::extractUri        

  # entity types
    dev_entity_types_get:
      path: /dev/entity/types/get
      controller: App\Development\Controller\EntityTypes::getEntityTypes

  # export
    dev_export:
      path: /dev/export/get
      controller: App\Development\Controller\Export::export

  # background_task
    dev_create_background_task:
      path: /dev/task/create
      controller: App\Development\Controller\BackgroundTasks::create

    # versions
    dev_version_service:
        path: /dev/version/service
        controller: App\Development\Controller\Version::getVersionService

    dev_versions_get:
        path: /dev/version/getAll
        controller: App\Development\Controller\Version::getVersions

  # clients
    dev_clients_get:
      path: /dev/clients/getAll
      controller: App\Development\Controller\Client::getAllClients

    dev_fetch_clients:
      path: /dev/clients/fetch
      controller: App\Development\Controller\Client::getFetchClients
